name: node-js feature
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
env:
  project: ${{ inputs.project }}
  component: ${{ inputs.component }}
jobs:
  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7
      - name: read version
        run: |
          ls -l
      - name: read version1
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: print version
        run: 
          echo "version is ${{ steps.version.outputs.version }}"